### ISSUE TITLE
Diary entry is missing indentation

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/erskine-childers_the-riddle-of-the-sands#5]
There are three sections in [chapter 15](https://github.com/standardebooks/erskine-childers_the-riddle-of-the-sands/blob/master/src/epub/text/chapter-15.xhtml) inside a `<div epub:type="z3998:diary-entry">`. For reasons that aren't clear to me, the first paragraph in each of these `div` blocks isn't indented.

The standard ebooks page appears to be down right now (?), so I can't confirm whether or not this might have been fixed already, or might be specific to my ereader.

**Comment by acabal** [comment]
These should have been blockquotes with margins, this should be fixed now. Thanks!
